# Generated by Django 5.1.3 on 2024-11-18 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KainTenun',
            fields=[
                ('idKainTenun', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Kain Tenun')),
                ('namaKainTenun', models.CharField(default='', max_length=100, verbose_name='Nama Kain Tenun')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('deskripsiKainTenun', models.CharField(max_length=100, verbose_name='Deskripsi Kain Tenun')),
            ],
            options={
                'verbose_name_plural': 'Kain Tenun',
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('idPembeli', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Pembeli')),
                ('namaDepan', models.CharField(max_length=35, verbose_name='Nama Depan')),
                ('namaBelakang', models.CharField(max_length=35, verbose_name='Nama Belakang')),
                ('jenisKelamin', models.CharField(max_length=10, verbose_name='Jenis Kelamin')),
                ('tanggalLahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('pekerjaan', models.CharField(max_length=35, verbose_name='Pekerjaan')),
                ('alamat', models.TextField(verbose_name='Alamat')),
            ],
            options={
                'verbose_name_plural': 'Pembeli',
            },
        ),
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('idToko', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Toko')),
                ('namaToko', models.CharField(default='', max_length=50, verbose_name='Nama Toko')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
            ],
            options={
                'verbose_name_plural': 'Toko',
            },
        ),
        migrations.CreateModel(
            name='NomorHp',
            fields=[
                ('idNomorHp', models.AutoField(primary_key=True, serialize=False)),
                ('nomorHp', models.CharField(max_length=15, verbose_name='Nomor HP')),
                ('idPembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.pembeli')),
            ],
            options={
                'verbose_name_plural': 'Nomor HP',
            },
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('idPembelian', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalPembelian', models.DateField(verbose_name='Tanggal Pembelian')),
                ('idPembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.pembeli', verbose_name='ID Pembeli')),
                ('idToko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.toko', verbose_name='ID Toko')),
            ],
            options={
                'verbose_name_plural': 'Pembelian',
            },
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('idDetailPembelian', models.AutoField(primary_key=True, serialize=False)),
                ('idKainTenun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.kaintenun', verbose_name='ID Kain Tenun')),
                ('idPembelian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pembelian', to='pembelian.pembelian', verbose_name='ID Pembelian')),
            ],
            options={
                'verbose_name_plural': 'Detail Pembelian',
            },
        ),
        migrations.CreateModel(
            name='Kepemilikan',
            fields=[
                ('idKepemilikan', models.AutoField(primary_key=True, serialize=False)),
                ('stok', models.IntegerField(default=0, verbose_name='Stok')),
                ('idKainTenun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.kaintenun', verbose_name='ID Kain Tenun')),
                ('idToko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelian.toko', verbose_name='ID Toko')),
            ],
            options={
                'verbose_name_plural': 'Kepemilikan',
            },
        ),
    ]
