# Generated by Django 5.1.3 on 2024-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaintenun',
            name='deskripsiKainTenun',
            field=models.TextField(verbose_name='Deskripsi Kain Tenun'),
        ),
        migrations.AlterField(
            model_name='pembeli',
            name='jenisKelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin'),
        ),
    ]
